# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1youBWNd9Bo2PwnarGTps5hK8Fgi2dRhm
"""

print("Operasi: +, -, *, /")
operasi = input("Pilih operasi: ")
print("Kamu memilih:", operasi) #
a = float(input("Angka pertama: "))
b = float(input("Angka kedua: "))

if operasi == "+":
  print("Hasil:" , a + b)
elif operasi == "-":
  print("Hasil:" , a - b)
elif operasi == "*":
  print("Hasil:" , a * b)
elif operasi == "/":
  print("Hasil:" , a / b)
else:
  print("Operasi tidak dikenali.")